import sqlite3
from src.services.logger import logger


class BaseRepository:
    """
    The connection owner and audit spine for all v3core repositories.
    All concrete repositories inherit from this.
    """

    def __init__(self, db_path: str):
        self.db_path = db_path

    def _get_connection(self) -> sqlite3.Connection:
        """Single point of truth for all DB connections in v3core."""
        conn = sqlite3.connect(self.db_path)
        # Register the custom collation from the physical DB
        conn.create_collation(
            "UTF8_NOCASE",
            lambda s1, s2: (s1.lower() > s2.lower()) - (s1.lower() < s2.lower()),
        )
        return conn

    def _log_change(
        self,
        cursor: sqlite3.Cursor,
        table: str,
        record_id: int,
        field: str,
        old_val,
        new_val,
        batch_id: str,
    ) -> None:
        """
        Write one audit row to the existing ChangeLog table.
        No-ops silently if old_val == new_val (no real change).
        batch_id must be generated by the Service layer, not the repository.
        """
        if str(old_val) == str(new_val):
            return
        cursor.execute(
            """
            INSERT INTO ChangeLog
                (LogTableName, RecordID, LogFieldName,
                 OldValue, NewValue, BatchID)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                table,
                record_id,
                field,
                str(old_val) if old_val is not None else None,
                str(new_val) if new_val is not None else None,
                batch_id,
            ),
        )
        logger.debug(
            f"[BaseRepository] Audit written: {table}.{field} (ID: {record_id})"
        )
